// Minimal, deliberately-scoped Markdown -> HTML conversion for publishing.
//
// Scope is the exact subset lib/agents/index.ts's writeContent() actually
// emits: ATX headings, paragraphs, unordered and ordered lists, bold, italic,
// links and images. Nothing else is claimed. Tables, footnotes, nested lists,
// blockquotes, code fences and raw HTML pass through as escaped plain text
// rather than being half-rendered -- a visible plain line on a customer's page
// is recoverable; silently mangled markup is not.
//
// A dependency would be the obvious answer, but publishing runs inside a 60s
// serverless function in a project with seven runtime dependencies total, and
// the input is machine-generated by a prompt this repo controls. That makes a
// small, exact, tested converter the honest choice over an unpinned parser.
//
// Escaping happens BEFORE any tag is emitted, so model output can never inject
// markup into a customer's site.

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Only http(s) and site-relative targets. Blocks javascript:/data: URLs. */
function safeHref(raw: string): string | null {
  const href = raw.trim();
  if (/^https?:\/\//i.test(href)) return href;
  if (href.startsWith("/") && !href.startsWith("//")) return href;
  if (href.startsWith("#")) return href;
  return null;
}

/** Inline formatting, applied to already-escaped text. */
function inline(escaped: string): string {
  let out = escaped;

  // Images before links -- "![alt](src)" also matches the link pattern.
  out = out.replace(/!\[([^\]]*)\]\(([^)\s]+)\)/g, (m, alt: string, src: string) => {
    const href = safeHref(src);
    return href ? `<img src="${href}" alt="${alt}" />` : m;
  });

  out = out.replace(/\[([^\]]+)\]\(([^)\s]+)\)/g, (m, text: string, target: string) => {
    const href = safeHref(target);
    return href ? `<a href="${href}">${text}</a>` : m;
  });

  out = out.replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
  // Single-asterisk italics, but not the inner asterisks of a bold run.
  out = out.replace(/(^|[^*])\*([^*\n]+)\*(?!\*)/g, "$1<em>$2</em>");

  return out;
}

type Block = { kind: "ul" | "ol"; items: string[] };

export function markdownToHtml(markdown: string): string {
  const lines = markdown.replace(/\r\n/g, "\n").split("\n");
  const html: string[] = [];
  let paragraph: string[] = [];
  let list: Block | null = null;

  const flushParagraph = () => {
    if (!paragraph.length) return;
    html.push(`<p>${inline(escapeHtml(paragraph.join(" ").trim()))}</p>`);
    paragraph = [];
  };
  const flushList = () => {
    if (!list) return;
    const items = list.items.map((i) => `<li>${inline(escapeHtml(i))}</li>`).join("");
    html.push(`<${list.kind}>${items}</${list.kind}>`);
    list = null;
  };
  const flushAll = () => { flushParagraph(); flushList(); };

  for (const rawLine of lines) {
    const line = rawLine.trimEnd();

    if (!line.trim()) { flushAll(); continue; }

    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading) {
      flushAll();
      const level = heading[1].length;
      html.push(`<h${level}>${inline(escapeHtml(heading[2].trim()))}</h${level}>`);
      continue;
    }

    const ul = line.match(/^\s*[-*+]\s+(.*)$/);
    if (ul) {
      flushParagraph();
      if (list?.kind !== "ul") { flushList(); list = { kind: "ul", items: [] }; }
      list.items.push(ul[1].trim());
      continue;
    }

    const ol = line.match(/^\s*\d+[.)]\s+(.*)$/);
    if (ol) {
      flushParagraph();
      if (list?.kind !== "ol") { flushList(); list = { kind: "ol", items: [] }; }
      list.items.push(ol[1].trim());
      continue;
    }

    flushList();
    paragraph.push(line.trim());
  }

  flushAll();
  return html.join("\n");
}

/** Plain-text excerpt for platforms that want one alongside the body. */
export function excerptFrom(markdown: string, maxLen = 155): string {
  const firstPara = markdown
    .split("\n")
    .find((l) => l.trim() && !/^[#>\-*+\d]/.test(l.trim()));
  if (!firstPara) return "";
  const text = firstPara
    .replace(/!\[[^\]]*\]\([^)]*\)/g, "")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replace(/[*_`]/g, "")
    .trim();
  return text.length > maxLen ? text.slice(0, maxLen - 1).trimEnd() + "…" : text;
}
