import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/supabase";
import { callClaude, extractJSON } from "@/lib/anthropic";
import { requireAuth, isAuthError, requireBrandAccess } from "@/lib/auth";

export const maxDuration = 60;

// Dynamic AI recommendations — generated by Claude from live data,
// cached server-side in the reports table for 4 hours per brand+section.
export async function GET(req: NextRequest) {
  const auth = await requireAuth(req);
  if (isAuthError(auth)) return auth;

  const url = new URL(req.url);
  const brandId = url.searchParams.get("brand");
  if (!brandId) return NextResponse.json({ error: "brand required" }, { status: 400 });
  const accessErr = requireBrandAccess(auth, brandId);
  if (accessErr) return accessErr;

  const section = "intelligence_recommendations";

  // Check server-side cache (reports table with section + cache_expires_at)
  const { data: cached } = await db
    .from("reports")
    .select("summary, cache_expires_at")
    .eq("brand_id", brandId)
    .eq("section", section)
    .gt("cache_expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(1);

  if (cached?.[0]?.summary) {
    try {
      return NextResponse.json({ recommendations: JSON.parse(cached[0].summary), cached: true });
    } catch { /* cache parse failed, regenerate */ }
  }

  // Gather live data for context
  const [{ data: brand }, { data: winners }, { data: opportunities }] = await Promise.all([
    db.from("brands").select("name, services, service_area").eq("id", brandId).single(),
    db.from("tracked_keywords").select("keyword, status, best_position, ai_opportunity_score, ai_opportunity_reason, search_volume")
      .eq("brand_id", brandId).in("status", ["improving", "declining"]).limit(10),
    db.from("tracked_keywords").select("keyword, best_position, ai_opportunity_score, ai_opportunity_reason, search_volume, estimated_monthly_clicks")
      .eq("brand_id", brandId).gte("ai_opportunity_score", 60).order("ai_opportunity_score", { ascending: false }).limit(10),
  ]);

  const aiText = await callClaude({
    maxTokens: 2000,
    user: `You are a senior SEO strategist advising ${brand?.name} (${brand?.services} in ${brand?.service_area}).

Based on this live data, generate 5-8 prioritized recommendations.

DECLINING KEYWORDS: ${JSON.stringify(winners?.filter(k => k.status === "declining").slice(0, 5))}
IMPROVING KEYWORDS: ${JSON.stringify(winners?.filter(k => k.status === "improving").slice(0, 5))}
TOP OPPORTUNITIES: ${JSON.stringify(opportunities?.slice(0, 8))}

Each recommendation must be immediately actionable with a one-click action.

Return ONLY JSON array:
[{
  "priority": 1-10,
  "category": "keyword|content|backlink|technical|local",
  "title": "short action title",
  "explanation": "2-3 sentences explaining what to do and why — speak directly to the business owner, no SEO jargon",
  "estimated_impact": "plain English estimate e.g. could bring 3-8 more calls/month",
  "action_type": "improve_content|fix_meta|generate_faq|build_backlinks|rewrite_page|boost_page1",
  "action_label": "button label e.g. Improve this page",
  "action_payload": {"target_keyword": "...", "target_url": "..."}
}]`,
  }).catch(() => null);

  const recommendations = extractJSON<unknown[]>(aiText || "") || [];

  // Store in cache (expires 4 hours from now)
  const expiresAt = new Date(Date.now() + 4 * 3600_000).toISOString();
  try { await db.from("reports").insert({
    brand_id: brandId,
    section,
    summary: JSON.stringify(recommendations),
    cache_expires_at: expiresAt,
    created_at: new Date().toISOString(),
  }); } catch {} // insert only; old rows expire naturally via cache_expires_at

  return NextResponse.json({ recommendations, cached: false });
}
