import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/supabase";
import { callClaude, extractJSON, type CallMeta } from "@/lib/anthropic";
import { requireAuth, isAuthError, requireBrandAccess } from "@/lib/auth";

export const maxDuration = 60;

// Dynamic AI recommendations — generated by Claude from live data,
// cached server-side in the reports table for 4 hours per brand+section.
export async function GET(req: NextRequest) {
  const auth = await requireAuth(req);
  if (isAuthError(auth)) return auth;

  const url = new URL(req.url);
  const brandId = url.searchParams.get("brand");
  if (!brandId) return NextResponse.json({ error: "brand required" }, { status: 400 });
  const accessErr = requireBrandAccess(auth, brandId);
  if (accessErr) return accessErr;

  const section = "intelligence_recommendations";

  // Check server-side cache (reports table with section + cache_expires_at)
  const { data: cached } = await db
    .from("reports")
    .select("summary, cache_expires_at")
    .eq("brand_id", brandId)
    .eq("section", section)
    .gt("cache_expires_at", new Date().toISOString())
    .order("created_at", { ascending: false })
    .limit(1);

  if (cached?.[0]?.summary) {
    try {
      return NextResponse.json({ recommendations: JSON.parse(cached[0].summary), cached: true });
    } catch { /* cache parse failed, regenerate */ }
  }

  // Gather live data for context
  const [{ data: brand }, { data: winners }, { data: opportunities }] = await Promise.all([
    db.from("brands").select("name, services, service_area").eq("id", brandId).single(),
    db.from("tracked_keywords").select("keyword, status, best_position, ai_opportunity_score, ai_opportunity_reason, search_volume")
      .eq("brand_id", brandId).in("status", ["improving", "declining"]).limit(10),
    db.from("tracked_keywords").select("keyword, best_position, ai_opportunity_score, ai_opportunity_reason, search_volume, estimated_monthly_clicks")
      .eq("brand_id", brandId).gte("ai_opportunity_score", 60).order("ai_opportunity_score", { ascending: false }).limit(10),
  ]);

  // thinking is ON by default and is billed against the SAME max_tokens as the
  // answer, so the old 2000 budget left too little room for the JSON array and
  // the reply was cut off mid-object — extractJSON then returned null and an
  // empty array got cached for 4 hours. Disable thinking and give the answer
  // headroom; the prompt itself is unchanged.
  let meta: CallMeta | null = null;
  let failure: string | null = null;

  const aiText = await callClaude({
    maxTokens: 8000,
    thinking: { type: "disabled" },
    onMeta: (m) => { meta = m; },
    user: `You are a senior SEO strategist advising ${brand?.name} (${brand?.services} in ${brand?.service_area}).

Based on this live data, generate 5-8 prioritized recommendations.

DECLINING KEYWORDS: ${JSON.stringify(winners?.filter(k => k.status === "declining").slice(0, 5))}
IMPROVING KEYWORDS: ${JSON.stringify(winners?.filter(k => k.status === "improving").slice(0, 5))}
TOP OPPORTUNITIES: ${JSON.stringify(opportunities?.slice(0, 8))}

Each recommendation must be immediately actionable with a one-click action.

Return ONLY JSON array:
[{
  "priority": 1-10,
  "category": "keyword|content|backlink|technical|local",
  "title": "short action title",
  "explanation": "2-3 sentences explaining what to do and why — speak directly to the business owner, no SEO jargon",
  "estimated_impact": "plain English estimate e.g. could bring 3-8 more calls/month",
  "action_type": "improve_content|fix_meta|generate_faq|build_backlinks|rewrite_page|boost_page1",
  "action_label": "button label e.g. Improve this page",
  "action_payload": {"target_keyword": "...", "target_url": "..."}
}]`,
  }).catch((err) => {
    failure = `model call failed: ${err instanceof Error ? err.message : String(err)}`;
    return null;
  });

  const parsed = extractJSON<unknown[]>(aiText || "");
  const recommendations = Array.isArray(parsed) ? parsed : [];

  // A cut-off reply can still parse into a shorter array, so treat max_tokens as
  // a failure on its own rather than trusting whatever survived.
  // `meta` is written from inside the onMeta callback, which control-flow
  // analysis cannot see -- it would otherwise narrow to the initial null.
  const m = meta as CallMeta | null;
  if (!failure) {
    if (m?.stop_reason === "max_tokens") {
      failure = `response truncated at max_tokens (${m.output_tokens} output tokens, ${m.thinking_tokens} thinking)`;
    } else if (!aiText) {
      failure = "model returned no text (see [callClaude] EMPTY TEXT above for stop_reason and token split)";
    } else if (!Array.isArray(parsed)) {
      failure = `could not parse a recommendation array from ${aiText.length} chars of model output`;
    }
  }

  console.log(
    `[recommendations] ${brandId}: stop_reason=${m?.stop_reason ?? "n/a"} ` +
    `input_tokens=${m?.input_tokens ?? 0} output_tokens=${m?.output_tokens ?? 0} ` +
    `thinking_tokens=${m?.thinking_tokens ?? 0} parsed=${failure ? "INCOMPLETE" : `${recommendations.length} recommendations`}`
  );

  // Never cache a partial or failed result — a 4-hour cache would pin the
  // empty state in the UI long after the underlying call would have succeeded.
  if (failure) {
    console.error(`[recommendations] ${brandId}: no recommendations generated — ${failure}`);
    return NextResponse.json({ recommendations: [], cached: false, error: failure });
  }

  // Store in cache (expires 4 hours from now)
  const expiresAt = new Date(Date.now() + 4 * 3600_000).toISOString();
  try { await db.from("reports").insert({
    brand_id: brandId,
    section,
    summary: JSON.stringify(recommendations),
    cache_expires_at: expiresAt,
    created_at: new Date().toISOString(),
  }); } catch {} // insert only; old rows expire naturally via cache_expires_at

  return NextResponse.json({ recommendations, cached: false });
}
